/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package design.patterns.study.jwhy

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import java.math.BigInteger

class SequenceTest {
    @Test
    @DisplayName("피보나치 테스트")
    fun fibonacciTest() {
        val fibonacci: Sequence<BigInteger> = sequence {
            var first = 0.toBigInteger()
            var second = 1.toBigInteger()
            while (true) {
                println("before first = ${first}")
                yield(first)
                println("after first = ${first}")
                val temp = first
                first += second
                second = temp
            }
        }

        println(fibonacci.take(10).toList())
    }
}
